INSERT INTO "options"
    ("option", "correct", "question_id")
VALUES
    ('Lost', true, 1),
    ('Gained', false, 1),
    ('Paired up', false, 1),
    ('remains same', false, 1),
    ('Roasting', false, 2),
    ('Leaching', false, 2),
    ('Calcination', true, 2),
    ('Cupellation', false, 2),
    ('K', true, 3),
    ('C', false, 3),
    ('A', false, 3),
    ('B1', false, 3),
    ('Time', false, 4),
    ('Length', false, 4),
    ('Weight', true, 4),
    ('Mass', false, 4),
    ('Diopter', true, 5),
    ('Horse power', false, 5),
    ('Hertz', false, 5),
    ('Watt', false, 5),
    ('angular displacement', false, 6),
    ('angular velocity', true, 6),
    ('angular acceleration', false, 6),
    ('angular momentum', false, 6),
    ('Herbivores', false, 7),
    ('Carnivores', true, 7),
    ('Omnivores', false, 7),
    ('None of the above', false, 7),
    ('Herbivore', false, 8),
    ('Carnivore', false, 8),
    ('Omnivore', true, 8),
    ('None of the above', false, 8),
    ('Vitamin D', false, 9),
    ('Vitamin E', false, 9),
    ('Vitamin F', true, 9),
    ('Vitamin K', false, 9);
